# name: myapp
services:
  front:
    build: ./frontend
    ports:
      - 80:80
    restart: always
  server:
    build: ./server
    ports:
      - 3333:3333
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql
    user: mysql
    volumes:
      - mysql-volume:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=article1
    ports:
      - 3306:3306
    restart: always
volumes:
  mysql-volume:
