- name: copy build
  hosts: app

  tasks:
    - name: deploy
      shell:
        cmd: |
          sudo systemctl stop nginx
          sudo cd my/frontend/
          sudo cp -r build/* /usr/share/nginx/html/
