- name: copy build
  hosts: app

  become: true
  tasks:
    - name: install nginx
      command: amazon-linux-extras install -y nginx1

    - name: remove html
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: copy html
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/frontend/my/frontend/build/
        dest: /usr/share/nginx/html
        owner: ec2-user
        group: ec2-user
        mode: 600

    - name: start nginx
      command: systemctl start nginx
