- name: copy build
  hosts: app

  become: true
  tasks:
    - name: install nginx
      command: amazon-linux-extras install -y nginx1

    # - name: remove html
    #   file:
    #     path: /usr/share/nginx/html
    #     state: absent

    # - name: create html
    #   file:
    #     path: /usr/share/nginx/html
    #     state: directory

    - name: copy html
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/ASDF/my/frontend/build/
        dest: /usr/share/nginx/html
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: start nginx
      command: systemctl start nginx
