- name: copy build
  hosts: app
  remote_user: ec2-user
  become: true
  tasks:
    - name: install nginx
      command: amazon-linux-extras install -y nginx1

    - name: remove html
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html
      file:
        path: /usr/share/nginx/html
        state: directory

    - name: cp build
      shell:
        cmd: |
          pwd
          ls -l
          cd /my/frontend
          cp -r build/* /usr/share/nginx/html

    - name: start nginx
      command: systemctl start nginx
