- name: copy build
  hosts: app
  become: true

  tasks:
    - name: Tell the hots about our servers it might want to ssh to
      ansible.builtin.known_hosts:
        name: 10.1.1.133

    - name: install nginx
      command: amazon-linux-extras install -y nginx1

    - name: remove html
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: copy html
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/frontend/my/frontend/build/
        dest: /usr/share/nginx/html
        owner: ec2-user
        group: ec2-user
        mode: 600

    - name: start nginx
      command: systemctl start nginx
