- name: copy build
  hosts: app
  become: true
  tasks:
    - name: install node
      shell:
        cmd: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
          nvm install 16
          node -v

    - name: copy
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/backend/my/server
        dest: /home/ec2-user/
        owner: ec2-user
        group: ec2-user
        # mode: 0755
        ignore_errors: true

    - name: kill npm
      command: pkill -f 'npm start'
      ignore_errors: true

    - name: start npm
      shell:
        cmd: |
          cd /home/ec2-user
          npm start
