- name: copy build
  hosts: app
  become: true
  tasks:
    - name: install node
      shell:
        cmd: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 16
          node -v

    - name: kill npm
      command: pkill -f 'npm start'
      ignore_errors: true

    - name: start npm
      shell:
        cmd: |
          npm install
          npm start
