- name: backend
  hosts: app
  become: true
  become_user: root

  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/backend/my/server
        dest: /home/ec2-user/

    - name: node install
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        . ~/.nvm/nvm.sh
        nvm install 16
        cd /home/ec2-user/server
        npm install
        npm start
