- name: copy build
  hosts: app
  become: true
  tasks:
    - name: kill npm
      command: pkill -f 'npm start'
      ignore_errors: true

    - name: start npm
      shell:
        cmd: |
          npm start
