- name: copy build
  hosts: app
  become: true
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/backend/my/server/
        dest: /home/ec2-user/server/
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: kill npm
      command: pkill -f 'npm start'
      ignore_errors: true

    - name: start npm
      shell:
        cmd: |
          cd /home/ec2-user
          npm start
