- name: copy build
  hosts: app
  remote_user: ec2-user
  become: true
  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/backend/my/server
        dest: /home/ec2-user/

    - name: node install
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        . ~/.nvm/nvm.sh
        nvm install 16

    - name: npm install
      ansible.builtin.shell: |
        cd /home/ec2-user/server
        npm install

    # - name: kill npm
    #   command: pkill -f 'npm start'
    #   ignore_errors: true

    - name: start npm
      shell:
        cmd: |
          cd /home/ec2-user
          npm start
