- name: backend
  hosts: app
  become: true

  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/backend/my/server
        dest: /home/ec2-user/

    - name: yum install
      shell:
        cmd: |
          yum install -y git
          yum install -y zsh
          sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
          source ~/.zshrc

    - name: node install
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        . ~/.nvm/nvm.sh
        nvm install 16

    - name: npm install
      ansible.builtin.shell: |
        cd /home/ec2-user/server
        npm install

    - name: start npm
      shell:
        cmd: |
          cd /home/ec2-user
          npm start
