apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dev
spec:
  provider:
    amiFamily: Bottlerocket
    tags:
      accountingEC2Tag: karpenter
      # eks/nodegroup-name: karpenter-group
      eks/cluster-name: my-cluster
    subnetSelector:
      Name: "karpenter.sh/discovery/my-cluster*"
    securityGroupSelector:
      kubernetes.io/cluster/my-cluster: owned
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.large"]
  ttlSecondsAfterEmpty: 30
  taints:
    - key: dedicated
      value: dev
      effect: NoSchedule
  labels:
    deployment: dev
