apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: dev
spec:
  taints:
    - key: dev
      value: "true"
      effect: NoSchedule
  labels:
    nodeType: AL2023_x86_64_STANDARD
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.large"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2c"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  providerRef:
    name: dev-lt
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 1209600
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: dev-lt
spec:
  subnetSelector:
    karpenter.sh/discovery/my-cluster: "*"
  securityGroupSelector:
    aws:eks:cluster-name: my-cluster # do not change
  tags:
    karpenter.sh/discovery: my-cluster
