apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: leesanghoon94/my-server:latest
          ports:
            - containerPort: 3333
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "12345678"
            - name: MYSQL_DATABASE
              value: "article1"
